// Main application types
export const MASTER_LOGIN_USER = 'MASTER_LOGIN_USER';
export const MASTER_LOGOUT_USER = 'MASTER_LOGOUT_USER';
export const MASTER_REGISTER_USER = 'MASTER_REGISTER_USER';
export const MASTER_SET_ALERT = 'MASTER_SET_ALERT';
export const MASTER_SET_MULTI_ALERT = 'MASTER_SET_MULTI_ALERT';
export const MASTER_CLEAR_ALERT = 'MASTER_CLEAR_ALERT';
export const MASTER_REFRESHED_TOKEN = 'MASTER_REFRESHED_TOKEN';
export const MASTER_APP_STATUS_PROCESSING = 'MASTER_APP_STATUS_PROCESSING';
export const MASTER_APP_STATUS_IDLE = 'MASTER_APP_STATUS_IDLE';

export const USER_INDEX = 'USER_INDEX';
export const USER_STORE = 'USER_STORE';
export const USER_SHOW = 'USER_SHOW';
export const USER_UPDATE = 'USER_UPDATE';
export const USER_DELETE = 'USER_DELETE';
export const USER_TEST = 'USER_TEST';

export const CAROUSEL_CONTENT_INDEX = 'CAROUSEL_CONTENT_INDEX';
export const CAROUSEL_CONTENT_STORE = 'CAROUSEL_CONTENT_STORE';
export const CAROUSEL_CONTENT_SHOW = 'CAROUSEL_CONTENT_SHOW';
export const CAROUSEL_CONTENT_UPDATE = 'CAROUSEL_CONTENT_UPDATE';
export const CAROUSEL_CONTENT_DELETE = 'CAROUSEL_CONTENT_DELETE';
export const CAROUSEL_CONTENT_TEST = 'CAROUSEL_CONTENT_TEST';

export const VIDEO_CONTENT_INDEX = 'VIDEO_CONTENT_INDEX';
export const VIDEO_CONTENT_STORE = 'VIDEO_CONTENT_STORE';
export const VIDEO_CONTENT_SHOW = 'VIDEO_CONTENT_SHOW';
export const VIDEO_CONTENT_UPDATE = 'VIDEO_CONTENT_UPDATE';
export const VIDEO_CONTENT_DELETE = 'VIDEO_CONTENT_DELETE';
export const VIDEO_CONTENT_TEST = 'VIDEO_CONTENT_TEST';

export const CLIENT_CONTENT_INDEX = 'CLIENT_CONTENT_INDEX';
export const CLIENT_CONTENT_STORE = 'CLIENT_CONTENT_STORE';
export const CLIENT_CONTENT_SHOW = 'CLIENT_CONTENT_SHOW';
export const CLIENT_CONTENT_UPDATE = 'CLIENT_CONTENT_UPDATE';
export const CLIENT_CONTENT_DELETE = 'CLIENT_CONTENT_DELETE';
export const CLIENT_CONTENT_TEST = 'CLIENT_CONTENT_TEST';

export const MESSAGE_CONTENT_INDEX = 'MESSAGE_CONTENT_INDEX';
export const MESSAGE_CONTENT_STORE = 'MESSAGE_CONTENT_STORE';
export const MESSAGE_CONTENT_SHOW = 'MESSAGE_CONTENT_SHOW';
export const MESSAGE_CONTENT_UPDATE = 'MESSAGE_CONTENT_UPDATE';
export const MESSAGE_CONTENT_DELETE = 'MESSAGE_CONTENT_DELETE';
export const MESSAGE_CONTENT_TEST = 'MESSAGE_CONTENT_TEST';
